# Generated by Django 6.0.1 on 2026-01-27 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_car_stock'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WishlistItem',
        ),
    ]
