# Generated by Django 6.0.1 on 2026-01-27 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_delete_wishlistitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='car',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.car'),
        ),
    ]
